const $=s=>document.querySelector(s);
const screens=['joinScreen','lobbyScreen','gameScreen','resultsScreen'];
let socket=null,me=null,room=null,role='ROAMER',phase='lobby',phaseEndsAt=0,players=new Map(),chatLog=[],positions=new Map();
let keys={},joyVector={x:0,y:0},aim={x:1,y:0},localPos={x:.5,y:.5},deferredPrompt=null,lastChat=0;
let soloMode=false,soloDummies=[],soloTimer=null,mapIndex=0;
const WORLD={w:1536,h:1024};
const charSheet=new Image(); charSheet.src='characters.svg';
const show=id=>screens.forEach(x=>$('#'+x).classList.toggle('active',x===id));
const nameEl=$('#nameInput'); nameEl.value=localStorage.getItem('roamers-name')||'';
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});
$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('#installBtn').classList.add('hidden')}};
$('#showJoinBtn').onclick=()=>$('#codeBox').classList.remove('hidden');
function ensureName(){const n=nameEl.value.trim();if(!n){nameEl.focus();return null}localStorage.setItem('roamers-name',n);return n}
function playerId(){let id=localStorage.getItem('roamers-player-id');if(!id){id=crypto.randomUUID();localStorage.setItem('roamers-player-id',id)}return id}
function setConnection(text,online=false){$('#connection').textContent=text;$('#connection').className=`status ${online?'online':'offline'}`}
function connect(){if(socket)return socket;if(typeof io==='undefined'){setConnection('Offline');return null}socket=io({reconnection:true,reconnectionAttempts:Infinity,reconnectionDelay:500,reconnectionDelayMax:5000,timeout:10000});setConnection('Connecting');socket.on('connect',()=>{setConnection('Online',true);if(room&&me&&!soloMode)socket.emit('room:rejoin',{code:room.code,playerId:me.id})});socket.on('connect_error',()=>setConnection('Offline'));socket.on('disconnect',()=>setConnection('Offline'));bindSocket();return socket}
function bindSocket(){socket.on('room:state',applyState);socket.on('room:created',applyState);socket.on('room:joined',applyState);socket.on('room:error',e=>alert(e?.message||'Unable to join that room.'));socket.on('game:roleAssigned',r=>{role=r.toUpperCase();$('#roleBadge').textContent=role;$('#roleBadge').style.background=role==='HUNTER'?'#9f3e36':'#24533f'});socket.on('game:phaseChanged',d=>{if(d.mapIndex!==undefined)mapIndex=d.mapIndex;$('#mapLabel').textContent=MAP_NAMES[mapIndex];setPhase(d.phase,d.endsAt)});socket.on('game:mapAssigned',d=>{if(d?.mapIndex!==undefined){mapIndex=d.mapIndex;$('#mapLabel').textContent=MAP_NAMES[mapIndex]}});socket.on('player:positionUpdate',list=>{(Array.isArray(list)?list:Object.values(list)).forEach(p=>{positions.set(p.id,{x:p.x,y:p.y,tx:p.x,ty:p.y});if(p.id===me?.id)localPos={x:p.x,y:p.y}})});socket.on('player:eliminated',id=>{const p=players.get(id);if(p)p.status='eliminated';renderPlayers()});socket.on('chat:message',m=>{chatLog.push(m);if(chatLog.length>200)chatLog.shift();renderChat()});socket.on('game:ended',showResults)}
function applyState(s){room=s.room||s;if(s.me){me=s.me;localStorage.setItem('roamers-player-id',me.id)}if(s.players)players=new Map(s.players.map(p=>[p.id,p]));if(s.chatLog)chatLog=s.chatLog;$('#roomCode').textContent=room.code||'—';renderPlayers();renderChat();show('lobbyScreen')}
$('#createBtn').onclick=()=>{const n=ensureName();if(!n)return;const s=connect();if(s)s.emit('room:create',{name:n,playerId:playerId()})};
$('#joinBtn').onclick=()=>{const n=ensureName(),code=$('#codeInput').value.trim().toUpperCase();if(!n||!code)return;const s=connect();if(s)s.emit('room:join',{code,name:n,playerId:playerId()})};
$('#soloBtn').onclick=()=>startSolo(ensureName());
$('#copyCode').onclick=async()=>{if(room?.code)await navigator.clipboard?.writeText(room.code);$('#copyCode').textContent='Copied';setTimeout(()=>$('#copyCode').textContent='Copy code',1200)};
function renderPlayers(){const el=$('#players');el.innerHTML=[...players.values()].map(p=>`<div class="player"><div class="avatar" aria-hidden="true"></div><strong>${esc(p.name)}</strong>${p.id===room?.hostId?'<small>HOST</small>':''}${p.status==='eliminated'?'<small>OUT</small>':''}</div>`).join('');$('#startHint').textContent=players.size<3?'Need at least 3 players to start.':`${players.size} players ready.`}
function renderChat(){['chatMessages','gameChatMessages','resultChatMessages'].forEach(id=>{const el=$('#'+id);if(!el)return;el.innerHTML=chatLog.map(m=>`<div class="message"><b>${esc(m.name||'Player')}:</b> ${esc(m.text)}</div>`).join('');el.scrollTop=el.scrollHeight})}
function sendChat(input){const text=input.value.trim();if(!text||Date.now()-lastChat<500)return;lastChat=Date.now();input.value='';if(soloMode){chatLog.push({name:me?.name||nameEl.value,text});if(chatLog.length>100)chatLog.shift();renderChat();return}if(socket?.connected)socket.emit('chat:message',{text})}
[['chatForm','chatInput'],['gameChatForm','gameChatInput'],['resultChatForm','resultChatInput']].forEach(([f,i])=>$('#'+f).onsubmit=e=>{e.preventDefault();sendChat($('#'+i))});
$('#startBtn').onclick=()=>{if(socket)socket.emit('game:start',{hunterCountdown:+$('#hunterCountdown').value,hidePhaseDuration:+$('#hideDuration').value,huntPhaseDuration:+$('#huntDuration').value})};
function setPhase(p,ends){phase=p;phaseEndsAt=ends||0;if(p==='role_reveal'||p==='hiding'||p==='hunting'){show('gameScreen');$('#waiting').classList.toggle('hidden',!(p==='hiding'&&role==='HUNTER'));$('#fireBtn').classList.toggle('hidden',!(p==='hunting'&&role==='HUNTER'));$('#phaseLabel').textContent=p.replace('_',' ').toUpperCase()}if(p==='lobby')show('lobbyScreen')}
function showResults(r={}){phase='results';phaseEndsAt=0;show('resultsScreen');$('#resultTitle').textContent=r.result==='hunter_win'?'Hunter Wins!':'Roamers Survive!';$('#resultSub').textContent=r.summary||'Round complete.';$('#timeline').innerHTML=(r.eliminations||[]).map((x,i)=>`<div><strong>${i+1}. ${esc(x.name||x.playerId)}</strong> — ${x.timeRemaining??''}s remaining</div>`).join('');renderChat()}
$('#playAgain').onclick=()=>soloMode?startSolo(me?.name):socket?.emit('game:playAgain');
$('#returnLobby').onclick=()=>{if(soloMode){stopSolo();show('joinScreen');setConnection('Offline')}else socket?.emit('game:returnLobby')};
$('#chatToggle').onclick=()=>$('#gameChat').classList.toggle('open');
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d');
function resize(){const d=devicePixelRatio||1;canvas.width=innerWidth*d;canvas.height=(innerHeight-62)*d;canvas.style.width='100%';canvas.style.height='100%';ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function worldPoint(p){return{x:p.x*WORLD.w,y:p.y*WORLD.h}}function camera(){const w=innerWidth,h=innerHeight-62,scale=Math.max(w/WORLD.w,h/WORLD.h),viewW=w/scale,viewH=h/scale,meP=worldPoint(localPos);return{scale,viewW,viewH,x:clamp(meP.x-viewW/2,0,WORLD.w-viewW),y:clamp(meP.y-viewH/2,0,WORLD.h-viewH)}}
function draw(){const w=innerWidth,h=innerHeight-62,c=camera();ctx.clearRect(0,0,w,h);ctx.save();ctx.scale(c.scale,c.scale);ctx.translate(-c.x,-c.y);drawMap(mapIndex);drawWorldPlayers();ctx.restore();drawAimOverlay(c);requestAnimationFrame(draw)}
function rect(x,y,w,h,fill,stroke=null,lw=2){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.strokeRect(x,y,w,h)}}
function text(x,y,s,size=16,fill='#f5e6c8',align='left'){ctx.font=`700 ${size}px "Courier New",monospace`;ctx.fillStyle=fill;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(s,x,y)}
function tile(x,y,w,h,a,b){rect(x,y,w,h,a);rect(x+4,y+4,w-8,h-8,b)}
function tree(x,y,s=1){rect(x-5*s,y+14*s,10*s,18*s,'#5b3d27');ctx.fillStyle='#183f2b';ctx.beginPath();ctx.arc(x,y,22*s,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2f6940';ctx.beginPath();ctx.arc(x-12*s,y-10*s,16*s,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x+13*s,y-8*s,15*s,0,Math.PI*2);ctx.fill();rect(x-4*s,y-20*s,8*s,8*s,'#5f9144')}
function lamp(x,y){rect(x-2,y-30,4,30,'#3a2a20');rect(x-7,y-35,14,8,'#f6c866','#38291f',2)}function bench(x,y){rect(x,y,54,8,'#704a2d','#38291f',2);rect(x+5,y+10,7,14,'#493322');rect(x+42,y+10,7,14,'#493322')}function road(x,y,w,h){rect(x,y,w,h,'#30343a');for(let p=x+20;p<x+w-20;p+=70)rect(p,y+h/2-3,34,6,'#d5b86e')}
function building(x,y,w,h,roof='#7a3c2f',wall='#a47a54',label='SHOP'){rect(x,y,w,h,wall,'#33261e',4);rect(x-8,y-18,w+16,22,roof,'#2b211b',3);rect(x+w*.35,y+h-55,32,55,'#4b3324','#241b17',3);rect(x+18,y+35,38,28,'#f3bd58','#3b2a20',3);rect(x+w-56,y+35,38,28,'#f3bd58','#3b2a20',3);text(x+w/2,y+12,label,11,'#ffe3a0','center')}
function sign(x,y,s){rect(x,y,92,38,'#4d3528','#241b17',3);text(x+46,y+19,s,10,'#f4d9a0','center')}
function drawMap(i){if(i===0)return drawCity();if(i===1)return drawForest();if(i===2)return drawIndustrial();if(i===3)return drawPark();return drawVillage()}
function drawCity(){rect(0,0,WORLD.w,WORLD.h,'#26313a');road(0,340,WORLD.w,150);road(0,735,WORLD.w,150);road(705,0,180,WORLD.h);for(let x=30;x<1450;x+=180){building(x,45,145,250,x%360?'#74402d':'#4a5965',x%360?'#8e6d50':'#65737c',x%360?'BISTRO':'MART');tree(x-22,300,.75);lamp(x+155,325);bench(x+48,310)}for(let x=35;x<1450;x+=190){building(x,895,150,95,'#4b5660','#69766d','BOOKS');tree(x+160,850,.65)}rect(80,510,560,190,'#4d5a4e','#252b2d',4);rect(115,545,490,110,'#5c7159');for(let x=140;x<580;x+=75){tree(x,555,.55);bench(x-15,620)}sign(925,525,'CITY PARK');sign(1100,525,'RIVERDALE');for(let x=930;x<1420;x+=90)lamp(x,710);text(55,30,'RIVERDALE NIGHT DISTRICT',18,'#f7d38a');text(1100,315,'SLOW LIVE EXPLORE',15,'#e8d7b5')}
function drawForest(){rect(0,0,WORLD.w,WORLD.h,'#477844');rect(170,0,170,WORLD.h,'#2f6944');rect(1010,0,200,WORLD.h,'#315f3e');ctx.fillStyle='#2f83a5';ctx.beginPath();ctx.moveTo(50,0);ctx.lineTo(250,0);ctx.bezierCurveTo(120,180,360,300,220,500);ctx.bezierCurveTo(80,700,330,820,170,1024);ctx.lineTo(0,1024);ctx.lineTo(0,0);ctx.fill();road(350,0,110,1024);road(770,0,90,1024);for(let x=35;x<1500;x+=75)for(let y=30;y<980;y+=80)if(!(x>820&&x<1180&&y>200&&y<600))tree(x+(y%3)*9,y,0.75+(x%20)/100);building(910,180,330,220,'#3e5d49','#9a754c','FOREST FARM');for(let x=940;x<1210;x+=70){tree(x,475,.55);rect(x-18,500,38,25,'#4c7a37')}rect(1010,500,210,155,'#8aa348','#4b6332',3);for(let x=1030;x<1190;x+=40)rect(x,520,22,70,'#6b8e38');bench(540,560);bench(600,760);sign(500,900,'VILLAGE');sign(520,940,'LAKE');sign(560,980,'MOUNTAINS');lamp(470,600);lamp(690,700)}
function drawIndustrial(){rect(0,0,WORLD.w,WORLD.h,'#1d2930');road(0,300,WORLD.w,150);road(600,0,150,WORLD.h);road(1120,0,150,WORLD.h);for(let y=40;y<900;y+=220){building(30,y,420,150,'#303b46','#56616a','LOGISTICS');building(820,y,260,150,'#28333b','#515a60','INDUSTRIES')}for(let x=470;x<1080;x+=120)for(let y=500;y<850;y+=90)tile(x,y,92,62,['#6d3432','#334d60','#7b5b36','#315c59'][(x+y)%4],'#27343b');for(let x=60;x<1480;x+=95){lamp(x,285);lamp(x,460)}rect(40,680,380,260,'#263a40','#161d20',4);for(let x=65;x<380;x+=75)rect(x,735,55,90,'#536d73','#182226',3);text(230,900,'HARBOR STORAGE',18,'#e4c58e','center');sign(500,520,'LOADING ZONE');sign(925,510,'BIGGER FASTER');sign(1160,900,'IDEAS REALITY')}
function drawPark(){rect(0,0,WORLD.w,WORLD.h,'#356746');road(0,900,WORLD.w,124);rect(480,100,570,560,'#4c7b50','#203b2a',4);ctx.fillStyle='#246b80';ctx.beginPath();ctx.ellipse(765,350,190,130,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#76a84d';ctx.beginPath();ctx.arc(765,350,62,0,Math.PI*2);ctx.fill();for(let a=0;a<Math.PI*2;a+=Math.PI/4)bench(765+Math.cos(a)*270-25,350+Math.sin(a)*190);for(let x=50;x<1450;x+=100)tree(x,80,.7);for(let x=50;x<1450;x+=110)tree(x,820,.7);building(70,160,250,150,'#8a4b35','#9d7a55','PARK CAFE');sign(1180,180,'PLAYGROUND');rect(1210,260,180,160,'#bd9462','#493326',4);rect(1260,300,70,10,'#2f5f8b');rect(1275,310,10,70,'#523927');rect(1360,310,10,70,'#523927');lamp(390,170);lamp(1100,170);lamp(450,700);lamp(1080,700);sign(590,730,'PEACE PEOPLE');sign(820,730,'NATURE FRIENDS');text(760,850,'RIVERDALE CITY PARK',22,'#f3d6a0','center')}
function drawVillage(){rect(0,0,WORLD.w,WORLD.h,'#b98a43');road(0,430,WORLD.w,120);road(680,0,150,WORLD.h);for(let x=20;x<600;x+=150)building(x,70,120,180,['#a95035','#7d4d32','#6c5d3d'][x%3],'#c7975d','FARM');building(870,65,270,220,'#40586a','#9b7449','VILLAGE INN');building(80,690,210,170,'#a64f34','#bd8b55','BAKERY');building(1040,690,240,180,'#54483b','#8c6d4c','BLACKSMITH');rect(400,650,220,160,'#6d9c45','#49642f',3);for(let x=420;x<600;x+=38)for(let y=670;y<790;y+=38)rect(x,y,25,25,'#3e7b37');for(let x=40;x<1450;x+=100)tree(x,950,.65);for(let x=35;x<1450;x+=130)lamp(x,600);rect(1330,50,150,330,'#d5bf6b','#7c6331',3);for(let x=1350;x<1460;x+=35)rect(x,75,20,280,'#d2b94f');sign(420,520,'VILLAGE');sign(420,560,'FOREST');sign(420,600,'LAKE');sign(420,640,'MOUNTAINS');text(1000,420,'SAME PATHS NEW STORIES',17,'#5b351e','center')}
function drawWorldPlayers(){for(const [id,p] of positions){const meta=players.get(id);if(!meta)continue;const wp=worldPoint(p);ctx.globalAlpha=meta.status==='eliminated'?.35:1;const idx=Math.abs(hash(id))%12,sx=(idx%6)*64,sy=Math.floor(idx/6)*96;if(charSheet.complete)ctx.drawImage(charSheet,sx,sy,64,96,wp.x-28,wp.y-54,56,84);else rect(wp.x-12,wp.y-20,24,35,id===me?.id?'#df7041':'#f4ead4','#17251e',2);if(id===me?.id){ctx.strokeStyle='#fff3b0';ctx.lineWidth=3;ctx.beginPath();ctx.arc(wp.x,wp.y-18,35,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1}}
function drawAimOverlay(c){if(role!=='HUNTER'||phase!=='hunting')return;const w=innerWidth,h=innerHeight-62,mp=worldPoint(localPos),px=(mp.x-c.x)*c.scale,py=(mp.y-c.y)*c.scale,len=Math.min(Math.max(w,h)*.5,420);ctx.save();ctx.globalAlpha=.85;ctx.strokeStyle='#ff6650';ctx.lineWidth=4;ctx.setLineDash([14,10]);ctx.beginPath();ctx.moveTo(px,py-18);ctx.lineTo(px+aim.x*len,py-18+aim.y*len);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#ff8b65';ctx.beginPath();ctx.arc(px+aim.x*len,py-18+aim.y*len,6,0,Math.PI*2);ctx.fill();ctx.restore()}
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))|0;return h}
function move(){let x=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),y=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0);x+=joyVector.x;y+=joyVector.y;if(!x&&!y)return;const l=Math.hypot(x,y);x/=l;y/=l;localPos.x=clamp(localPos.x+x*.008,.03,.97);localPos.y=clamp(localPos.y+y*.008,.06,.94);if(soloMode)positions.set(me.id,{x:localPos.x,y:localPos.y});else if(socket)socket.emit('player:move',{dx:x,dy:y})}
addEventListener('keydown',e=>{keys[e.key]=true;if(e.key===' ')$('#fireBtn').click()});addEventListener('keyup',e=>{keys[e.key]=false});setInterval(move,50);
const joystick=$('#joystick'),stick=$('.stick');let joyPointer=null;
function updateJoy(e){const r=joystick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.38;let dx=e.clientX-cx,dy=e.clientY-cy,d=Math.hypot(dx,dy);if(d>max){dx=dx/d*max;dy=dy/d*max}joyVector={x:dx/max,y:dy/max};stick.style.transform=`translate(${dx}px,${dy}px)`}
function resetJoy(){joyPointer=null;joyVector={x:0,y:0};stick.style.transform='translate(0,0)'}
joystick.addEventListener('pointerdown',e=>{e.preventDefault();joyPointer=e.pointerId;joystick.setPointerCapture(e.pointerId);updateJoy(e)});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joyPointer)updateJoy(e)});joystick.addEventListener('pointerup',e=>{if(e.pointerId===joyPointer)resetJoy()});joystick.addEventListener('pointercancel',resetJoy);joystick.addEventListener('lostpointercapture',resetJoy);
let aimPointer=null;
function updateAimFromEvent(e){const c=camera(),mp=worldPoint(localPos),px=(mp.x-c.x)*c.scale,py=(mp.y-c.y)*c.scale,dx=e.clientX-px,dy=e.clientY-(py-18),d=Math.hypot(dx,dy);if(d<6)return;aim={x:dx/d,y:dy/d}}
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||e.clientY>90){aimPointer=e.pointerId;canvas.setPointerCapture(e.pointerId);updateAimFromEvent(e)}});canvas.addEventListener('pointermove',e=>{if(aimPointer===e.pointerId)updateAimFromEvent(e);else if(e.pointerType==='mouse'&&role==='HUNTER')updateAimFromEvent(e)});canvas.addEventListener('pointerup',e=>{if(e.pointerId===aimPointer)aimPointer=null});canvas.addEventListener('pointercancel',e=>{if(e.pointerId===aimPointer)aimPointer=null});
$('#fireBtn').onclick=()=>{if(soloMode)soloHunt();else socket?.emit('player:eliminate')};
setInterval(()=>{if(phaseEndsAt){const s=Math.max(0,Math.ceil((phaseEndsAt-Date.now())/1000));$('#timer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;$('#waitingTimer').textContent=s}},200);
function startSolo(n){if(!n)return;stopSolo();soloMode=true;me={id:'solo-'+playerId(),name:n};room={code:'SOLO',hostId:me.id};role='HUNTER';phase='role_reveal';chatLog=[];players=new Map();positions=new Map();soloDummies=[];localPos={x:.18,y:.5};mapIndex=Math.floor(Math.random()*5);$('#mapLabel').textContent=MAP_NAMES[mapIndex];players.set(me.id,{id:me.id,name:n,role:'HUNTER',status:'alive'});positions.set(me.id,{x:localPos.x,y:localPos.y});for(let i=0;i<5;i++){const id=`dummy-${i}`,x=.25+(i%3)*.25,y=.2+Math.floor(i/3)*.38;players.set(id,{id,name:`Practice Roamer ${i+1}`,role:'ROAMER',status:'alive'});positions.set(id,{x,y});soloDummies.push({id,x,y,targetX:x,targetY:y,nextChange:0})}$('#roleBadge').textContent='HUNTER';$('#roleBadge').style.background='#9f3e36';$('#fireBtn').classList.add('hidden');$('#waiting').classList.add('hidden');$('#gameChat').classList.remove('open');show('gameScreen');setConnection('Solo');soloPhase('role_reveal',3)}
function soloPhase(name,seconds){phase=name;phaseEndsAt=Date.now()+seconds*1000;$('#phaseLabel').textContent=name.replace('_',' ').toUpperCase();$('#fireBtn').classList.toggle('hidden',name!=='hunting');$('#waiting').classList.toggle('hidden',name!=='hiding');clearTimeout(soloTimer);soloTimer=setTimeout(()=>{if(name==='role_reveal')soloPhase('hiding',5);else if(name==='hiding')soloPhase('hunting',120);else soloFinish()},seconds*1000)}
function soloHunt(){if(phase!=='hunting')return;let best=null,bestDist=Infinity;for(const d of soloDummies){if(players.get(d.id)?.status==='eliminated')continue;const dx=d.x-localPos.x,dy=d.y-localPos.y,dist=Math.hypot(dx,dy),dot=(dx*aim.x+dy*aim.y)/(dist||1);if(dot>.72&&dist<.34&&dist<bestDist){best=d;bestDist=dist}}if(best){players.get(best.id).status='eliminated';renderPlayers();if(soloDummies.every(d=>players.get(d.id)?.status==='eliminated'))soloFinish()}}
function updateSolo(){if(!soloMode||phase!=='hunting')return;const now=Date.now();for(const d of soloDummies){if(players.get(d.id)?.status==='eliminated')continue;if(now>d.nextChange){d.targetX=clamp(d.targetX+(Math.random()-.5)*.3,.08,.92);d.targetY=clamp(d.targetY+(Math.random()-.5)*.3,.12,.88);d.nextChange=now+700+Math.random()*1200}d.x+=(d.targetX-d.x)*.02;d.y+=(d.targetY-d.y)*.02;positions.set(d.id,{x:d.x,y:d.y})}}
setInterval(updateSolo,50);
function soloFinish(){const alive=soloDummies.filter(d=>players.get(d.id)?.status!=='eliminated').length;showResults({result:alive?'roamer_win':'hunter_win',summary:alive?`${alive} practice roamers escaped.`:'All practice roamers were caught.',eliminations:soloDummies.filter(d=>players.get(d.id)?.status==='eliminated').map((d,i)=>({name:players.get(d.id)?.name,timeRemaining:0}))})}
function stopSolo(){clearTimeout(soloTimer);soloTimer=null;soloMode=false;soloDummies=[]}
const MAP_NAMES=['Riverdale Night','Whispering Forest','Northridge Harbor','Riverdale Park','Sunfield Village'];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
draw();
