import express from 'express';
import { createServer } from 'node:http';
import { randomUUID } from 'node:crypto';
import { Server } from 'socket.io';
import { obstacleSet, spawnSet } from './collision-map.mjs';
const app=express();const httpServer=createServer(app);const io=new Server(httpServer,{cors:{origin:'*'}});const rooms=new Map();const PORT=process.env.PORT||3000;const MAP_COUNT=5;const WORLD={w:1536,h:1024};const PLAYER_RADIUS=18;
app.disable('x-powered-by');app.get('/health',(_req,res)=>res.json({ok:true,game:'Roamers'}));app.use(express.static(process.cwd(),{index:false,extensions:false}));app.get('*',(_req,res)=>res.sendFile('index.html',{root:process.cwd()}));
const makeCode=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let code;do code=Array.from({length:5},()=>chars[Math.floor(Math.random()*chars.length)]).join('');while(rooms.has(code));return code};
function publicState(room,meId){return{room:{code:room.code,hostId:room.hostId,mapIndex:room.mapIndex},me:meId?room.players.get(meId):null,players:[...room.players.values()].map(({socketId,...p})=>p),chatLog:room.chatLog.slice(-100)}}
function broadcast(room){for(const p of room.players.values())if(p.socketId)io.to(p.socketId).emit('room:state',publicState(room,p.id))}
function endTimer(room){if(room.timer)clearTimeout(room.timer);room.timer=null}
function phase(room,name,seconds){room.phase=name;room.phaseEndsAt=Date.now()+seconds*1000;io.to(room.code).emit('game:phaseChanged',{phase:name,endsAt:room.phaseEndsAt,mapIndex:room.mapIndex});endTimer(room);room.timer=setTimeout(()=>advance(room),seconds*1000)}
function advance(room){if(room.phase==='role_reveal')return phase(room,'hiding',room.hideDuration);if(room.phase==='hiding')return phase(room,'hunting',room.huntDuration);if(room.phase==='hunting')return finish(room,'roamer_win')}
function finish(room,result){endTimer(room);room.phase='results';io.to(room.code).emit('game:ended',{result,summary:result==='hunter_win'?'The Hunter caught the roamers.':'The roamers survived the hunt.',eliminations:room.eliminations})}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function pointSegmentDistance(px,py,x1,y1,x2,y2){const dx=x2-x1,dy=y2-y1,len2=dx*dx+dy*dy;if(!len2)return Math.hypot(px-x1,py-y1);const t=clamp(((px-x1)*dx+(py-y1)*dy)/len2,0,1);return Math.hypot(px-(x1+dx*t),py-(y1+dy*t))}
function circleHitsRect(px,py,r,[x,y,w,h]){const cx=clamp(px,x,x+w),cy=clamp(py,y,y+h);return Math.hypot(px-cx,py-cy)<r}
function circleHitsObstacle(mapIndex,px,py,r=PLAYER_RADIUS){const o=obstacleSet(mapIndex);for(const rect of o.rects||[])if(circleHitsRect(px,py,r,rect))return true;for(const [cx,cy,cr] of o.circles||[])if(Math.hypot(px-cx,py-cy)<r+cr)return true;for(const [x1,y1,x2,y2] of o.segments||[])if(pointSegmentDistance(px,py,x1,y1,x2,y2)<r+4)return true;return false}
function lineBlocked(mapIndex,x1,y1,x2,y2){const o=obstacleSet(mapIndex);const dist=Math.hypot(x2-x1,y2-y1),steps=Math.max(1,Math.ceil(dist/6));for(let i=1;i<steps;i++){const t=i/steps,px=x1+(x2-x1)*t,py=y1+(y2-y1)*t;for(const rect of o.rects||[])if(circleHitsRect(px,py,1,rect))return true;for(const [cx,cy,cr] of o.circles||[])if(Math.hypot(px-cx,py-cy)<cr)return true;for(const [sx,sy,ex,ey] of o.segments||[])if(pointSegmentDistance(px,py,sx,sy,ex,ey)<4)return true}return false}
function applyMovement(room,p,dx,dy){const stepX=Number(dx)*.012*WORLD.w,stepY=Number(dy)*.012*WORLD.h;let x=(p.x??.5)*WORLD.w,y=(p.y??.5)*WORLD.h;const distance=Math.hypot(stepX,stepY),steps=Math.max(1,Math.ceil(distance/4));for(let i=0;i<steps;i++){const nx=x+stepX/steps,ny=y+stepY/steps;if(nx>=PLAYER_RADIUS&&nx<=WORLD.w-PLAYER_RADIUS&&!circleHitsObstacle(room.mapIndex,nx,y,PLAYER_RADIUS))x=nx;if(ny>=PLAYER_RADIUS&&ny<=WORLD.h-PLAYER_RADIUS&&!circleHitsObstacle(room.mapIndex,x,ny,PLAYER_RADIUS))y=ny}p.x=clamp(x/WORLD.w,.03,.97);p.y=clamp(y/WORLD.h,.06,.94)}
function startGame(room,settings={}){if(room.players.size<2)return;room.hunterCountdown=Math.max(5,Math.min(30,Number(settings.hunterCountdown)||15));room.hideDuration=Math.max(10,Math.min(60,Number(settings.hidePhaseDuration)||15));room.huntDuration=Math.max(60,Math.min(600,Number(settings.huntPhaseDuration)||200));room.mapIndex=Math.floor(Math.random()*MAP_COUNT);const ids=[...room.players.keys()],hunter=ids[Math.floor(Math.random()*ids.length)],spawns=spawnSet(room.mapIndex);room.hunterId=hunter;room.eliminations=[];ids.forEach((id,i)=>{const p=room.players.get(id),s=spawns[i%spawns.length];p.role=id===hunter?'HUNTER':'ROAMER';p.status='alive';p.x=s.x;p.y=s.y;p.aimX=1;p.aimY=0});for(const p of room.players.values())if(p.socketId)io.to(p.socketId).emit('game:roleAssigned',p.role);io.to(room.code).emit('game:mapAssigned',{mapIndex:room.mapIndex});phase(room,'role_reveal',room.hunterCountdown);broadcast(room)}
io.on('connection',socket=>{
 socket.on('room:create',({name,playerId})=>{const code=makeCode(),id=playerId||randomUUID(),player={id,socketId:socket.id,name:String(name||'Player').slice(0,24),spriteIndex:0,status:'alive',role:'ROAMER',x:.5,y:.5,aimX:1,aimY:0},room={code,hostId:id,mapIndex:0,players:new Map([[id,player]]),chatLog:[],phase:'lobby',timer:null,eliminations:[],hideDuration:15,huntDuration:200,hunterCountdown:15};rooms.set(code,room);socket.join(code);socket.data.roomCode=code;socket.data.playerId=id;socket.emit('room:created',publicState(room,id))});
 socket.on('room:join',({code,name,playerId})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room||room.phase!=='lobby')return socket.emit('room:error',{message:'Room not found or already started.'});const id=playerId||randomUUID();if(room.players.has(id))return socket.emit('room:error',{message:'That player is already in the room.'});const player={id,socketId:socket.id,name:String(name||'Player').slice(0,24),spriteIndex:room.players.size%12,status:'alive',role:'ROAMER',x:.5,y:.5,aimX:1,aimY:0};room.players.set(id,player);socket.join(room.code);socket.data.roomCode=room.code;socket.data.playerId=id;socket.emit('room:joined',publicState(room,id));broadcast(room)});
 socket.on('room:rejoin',({code,playerId})=>{const room=rooms.get(String(code||'').toUpperCase()),player=room?.players.get(playerId);if(!room||!player)return;player.socketId=socket.id;socket.join(room.code);socket.data.roomCode=room.code;socket.data.playerId=playerId;socket.emit('room:state',publicState(room,playerId));if(room.phase!=='lobby')socket.emit('game:roleAssigned',player.role);if(room.phase!=='lobby')socket.emit('game:phaseChanged',{phase:room.phase,endsAt:room.phaseEndsAt,mapIndex:room.mapIndex})});
 socket.on('game:start',settings=>{const room=rooms.get(socket.data.roomCode);if(room&&room.hostId===socket.data.playerId)startGame(room,settings)});
 socket.on('player:move',({dx=0,dy=0})=>{const room=rooms.get(socket.data.roomCode),p=room?.players.get(socket.data.playerId);if(!p||!room||room.phase==='lobby'||room.phase==='results'||p.status==='eliminated')return;const mx=Number(dx),my=Number(dy),ml=Math.hypot(mx,my);if(ml>.05){p.aimX=mx/ml;p.aimY=my/ml}applyMovement(room,p,mx,my);io.to(room.code).emit('player:positionUpdate',[...room.players.values()].map(x=>({id:x.id,x:x.x??.5,y:x.y??.5}))) });
 socket.on('player:eliminate',({aimX,aimY}={})=>{const room=rooms.get(socket.data.roomCode),hunter=room?.players.get(socket.data.playerId);if(!room||room.phase!=='hunting'||hunter?.role!=='HUNTER')return;const rawX=Number(aimX),rawY=Number(aimY);const ax=Number.isFinite(rawX)?rawX:hunter.aimX,ay=Number.isFinite(rawY)?rawY:hunter.aimY,al=Math.hypot(ax,ay);if(!al)return;const nx=ax/al,ny=ay/al;hunter.aimX=nx;hunter.aimY=ny;const MAX_RANGE=.42,TARGET_RADIUS=.045,hx=hunter.x*WORLD.w,hy=hunter.y*WORLD.h;let target=null,bestAlong=Infinity;for(const p of room.players.values()){if(p.role!=='ROAMER'||p.status==='eliminated')continue;const tx=p.x*WORLD.w,ty=p.y*WORLD.h,dx=tx-hx,dy=ty-hy,along=dx*nx+dy*ny;if(along<=0||along>MAX_RANGE*WORLD.w)continue;const perpendicular=Math.abs(dx*ny-dy*nx);if(perpendicular>TARGET_RADIUS*WORLD.w)continue;if(lineBlocked(room.mapIndex,hx,hy,tx,ty))continue;if(along<bestAlong){target=p;bestAlong=along}}if(!target)return;target.status='eliminated';room.eliminations.push({name:target.name,playerId:target.id,timeRemaining:Math.max(0,Math.ceil((room.phaseEndsAt-Date.now())/1000))});io.to(room.code).emit('player:eliminated',target.id);if(![...room.players.values()].some(p=>p.role==='ROAMER'&&p.status!=='eliminated'))finish(room,'hunter_win')});
 socket.on('chat:message',({text})=>{const room=rooms.get(socket.data.roomCode),p=room?.players.get(socket.data.playerId);if(!room||!p||!String(text||'').trim())return;const message={name:p.name,text:String(text).trim().slice(0,300),at:Date.now()};room.chatLog.push(message);io.to(room.code).emit('chat:message',message)});
 socket.on('game:playAgain',()=>{const room=rooms.get(socket.data.roomCode);if(room&&room.hostId===socket.data.playerId)startGame(room,room)});
 socket.on('game:returnLobby',()=>{const room=rooms.get(socket.data.roomCode);if(!room)return;endTimer(room);room.phase='lobby';room.phaseEndsAt=0;room.hunterId=null;room.mapIndex=0;for(const p of room.players.values()){p.role='ROAMER';p.status='alive'}io.to(room.code).emit('game:phaseChanged',{phase:'lobby',endsAt:0,mapIndex:0});broadcast(room)});
 socket.on('disconnect',()=>{const room=rooms.get(socket.data.roomCode),p=room?.players.get(socket.data.playerId);if(p&&p.socketId===socket.id)p.socketId=null});
});
httpServer.listen(PORT,'0.0.0.0',()=>console.log(`Roamers server listening on ${PORT}`));
